### ISSUE TITLE
LiveCode for python don't work.

### ISSUE THREAD

**Issue by ghost** [Xirider/LiveCode#17]
Hello, when I launch LiveCode for python on a python code, a new panel appear and show me those lines :

Print Output:
Traceback (most recent call last):
  File "c:\Users\leandre\.vscode\extensions\xirider.livecode-1.3.10\node_modules\arepl-backend\python\arepl_python_evaluator.py", line 11, in <module>
    import astunparse
  File "c:\Users\leandre\.vscode\extensions\xirider.livecode-1.3.10\node_modules\arepl-backend\python\astunparse\__init__.py", line 3, in <module>
    from six.moves import cStringIO
ModuleNotFoundError: No module named 'six.moves'

I've tried to pip install six and astunparse, but they're already installed. I've searched on the internet, but nobody got the same error, so I don't know I could've done for this error, but now I cannot use the extension.

If someone could help me please.

**Comment by dog2000413** [comment]
+ 1 encountering same issue and both are installed as well.

**Comment by ech678** [comment]
me too

**Comment by Cresol3127** [comment]
this might help you: [https://github.com/Xirider/LiveCode/pull/22](url)
