### ISSUE TITLE
Live Code dont work

### ISSUE THREAD

**Issue by azazel912** [Xirider/LiveCode#18]
Hello, I encountered an error that does not allow me to open the live code, after I run it I see this text 
Print Output:
Traceback (most recent call last):
File "c:\Users\leandre.vscode\extensions\xirider.livecode-1.3.10\node_modules\arepl-backend\python\arepl_python_evaluator.py", line 11, in
import astunparse
File "c:\Users\leandre.vscode\extensions\xirider.livecode-1.3.10\node_modules\arepl-backend\python\astunparse_init_.py", line 3, in
from six.moves import cStringIO
ModuleNotFoundError: No module named 'six.moves'
I tried to somehow solve this problem or find a solution on the Internet but it didn’t help, please help me with my problem, thanks in advance

**Comment by RickeyChen0805** [comment]
me to!

**Comment by UniXingKong** [comment]
I have same problem.

**Comment by TheTommyUknow** [comment]
same here, find any solution?

**Comment by TheTommyUknow** [comment]
@Xirider, hey, this issue is still unresolved and it really needs to be fixed, thank you.

**Comment by qq1073972124** [comment]
go to the given path and edit __init__.py
change line 3 to:  from io import StringIO
change all cStringIO to StringIO

**Comment by MicalWillen** [comment]
> go to the given path and edit **init**.py change line 3 to: from io import StringIO change all cStringIO to StringIO

no use

**Comment by qq1073972124** [comment]
> > go to the given path and edit **init**.py change line 3 to: from io import StringIO change all cStringIO to StringIO
> 
> no use

for me print statement and error message is working but it still wont show variables

**Comment by Slimaure** [comment]
> go to the given path and edit **init**.py change line 3 to: from io import StringIO change all cStringIO to StringIO

Works for me

**Comment by ndawghoodstar** [comment]
Same issue, changing cstring to string doesn't work

**Comment by apitofme** [comment]
The issue appears to be in the [python-astunparse](https://github.com/simonpercivall/astunparse) module rather than the **Live Code** extension itself (or the `python-six` module). Perhaps this issue needs to be reported there?
<br />


> go to the given path and edit **init**.py change line 3 to: from io import StringIO change all cStringIO to StringIO

I do **not** like the idea of editing 3rd-Party source files directly, my feeling is that it should be fixed _**at source**_ for everyone.

However since the issue seems to originate "upstream" I have tried this solution and it _does_ work for me. Although I would appreciate clarification -- _Answer's with explanations are always best  ;)_
i.e. What is the _cause_ of the problem and _why_ does this action solve it?


The [python-six module](https://pypi.org/project/six/) is a compatibility layer between Python 2.x and Python 3.x, wherein the [six.moves](https://six.readthedocs.io/#module-six.moves) module is used to 'provide a consistent interface' for certain functions that have been relocated to different modules in Python 3.x.

So all we're doing is changing the import statement to refer to the _standard_ **io** module rather than reference one via **six** (where I assume "_cStringIO_" refers to a pre-compiled module's static source file in C), then simply updating the references.
<br />

I do not know how dependent on or how closely tied to these external modules the **Live Code** extension is, however some investigating on my part seems to suggest that [since Python 3.9 the `astunparse` module may no longer be required](https://github.com/simonpercivall/astunparse/issues/67#issuecomment-1438351272) as equivalent functionality is now included in the standard library.
<br />

Some sort of "official" clarification on this issue would be much appreciated.

**Comment by Almenon** [comment]
While you're waiting for Xirider to fix this, you could use https://github.com/Almenon/AREPL-vscode as an alterative. It's a VSCode extension similar to LiveCode (the codebase was forked from AREPL-vscode, actually). AREPL-vscode does not have this problem as it does not use astunparse.

**Comment by leandrofelipesantanna** [comment]
> While you're waiting for Xirider to fix this, you could use https://github.com/Almenon/AREPL-vscode as an alterative. It's a VSCode extension similar to LiveCode (the codebase was forked from AREPL-vscode, actually). AREPL-vscode does not have this problem as it does not use astunparse.

**Awesome tip!!!
It works very well.**

**Comment by xuerff** [comment]
C:\Users\ you name \.vscode\extensions\xirider.livecode-1.3.10\node_modules\arepl-backend\python\astunparse\__init__.py

`# coding: utf-8
from __future__ import absolute_import
from six import StringIO
from .unparser import Unparser
from .printer import Printer


__version__ = '1.6.3'


def unparse(tree):
    v = StringIO()
    Unparser(tree, file=v)
    return v.getvalue()


def dump(tree):
    v = StringIO()
    Printer(file=v).visit(tree)
    return v.getvalue()`

**Comment by Cresol3127** [comment]
this might help you: [https://github.com/Xirider/LiveCode/pull/22](url)
make sure you have installed astunparse module by running `pip install astunparse` in command prompt (windows)

**Comment by DaniNocchi** [comment]
How i fixed it (Only for Python 3.X)

I went to the error file (`C:\Users\[your pc name]\.vscode\extensions\xirider.livecode-1.3.10\node_modules\arepl-backend\python\astunparse`)

i opened the `__init__.py` file

i changed the `from six.moves` line to `from io import StringIO`

every `cStringIO` thing in this file, i changed to `StringIO` (basically only the double `v = StringIO()` lines)

That fix only works for python 3.X probably.
