### ISSUE TITLE
run extension error

### ISSUE THREAD

**Issue by VanHai93** [Xirider/LiveCode#21]
Hi there,

I'm experiencing an issue with the LiveCode extension in VS Code. Whenever I run the extension, I encounter the following error:

Traceback (most recent call last):
  File "c:\Users\Hai\.vscode\extensions\xirider.livecode-1.3.10\node_modules\arepl-backend\python\arepl_python_evaluator.py", line 11, in <module>
    import astunparse
  File "c:\Users\Hai\.vscode\extensions\xirider.livecode-1.3.10\node_modules\arepl-backend\python\astunparse\__init__.py", line 3, in <module>
    from six.moves import cStringIO
ModuleNotFoundError: No module named 'six.moves'
I have tried installing the six module using pip install six and have verified that it is installed. Despite this, the error persists. Could you please assist me in resolving this issue?

Thank you in advance for your help!

**Comment by raffaelewylde** [comment]
same

**Comment by C19Y-727** [comment]
Try replacing C:\Users\ username \.vscode\extensions\xirider.livecode-1.3.10\node_modules\arepl-backend\python. The following six.ph file or force it to upgrade

**Comment by logan-ul** [comment]
> Try replacing C:\Users\ username .vscode\extensions\xirider.livecode-1.3.10\node_modules\arepl-backend\python. The following six.ph file or force it to upgrade

im sorry what file?

**Comment by Cresol3127** [comment]
this might help you: [https://github.com/Xirider/LiveCode/pull/22](url)
make sure you have installed astunparse module by running `pip install astunparse` in command prompt (windows)

**Comment by JeffreyHu17** [comment]
> this might help you: [https://github.com/Xirider/LiveCode/pull/22](url) make sure you have installed astunparse module by running `pip install astunparse` in command prompt (windows)

it works, thanks
