### ISSUE TITLE
No module named 'six.moves'

### ISSUE THREAD

**Issue by ozliver** [Xirider/LiveCode#23]
Hi,

I  used LiveCode in vscode, but it reported error in a simple py code.

code is: 
`import os
import six
six_path = os.path.dirname(six.__file__)
print(f"six install: {six_path}")`

output is:
six install: D:\DevEnv\Python313\Lib\site-packages
[Done] exited with code=0 in 0.58 seconds

error is:
Print Output:
Traceback (most recent call last):
  File "c:\Users\DCao\.vscode\extensions\xirider.livecode-1.3.10\node_modules\arepl-backend\python\arepl_python_evaluator.py", line 11, in <module>
    import astunparse
  File "c:\Users\DCao\.vscode\extensions\xirider.livecode-1.3.10\node_modules\arepl-backend\python\astunparse\__init__.py", line 3, in <module>
    from six.moves import cStringIO
ModuleNotFoundError: No module named 'six.moves'

I have installed astunparse and six modules, so it's wired

**Comment by rairay91** [comment]
Same problem in my case.

here is the complete error message-
> Print Output:
Traceback (most recent call last):
  File "/home/hp/.vscode/extensions/xirider.livecode-1.3.10/node_modules/arepl-backend/python/arepl_python_evaluator.py", line 11, in <module>
    import astunparse
  File "/home/hp/.vscode/extensions/xirider.livecode-1.3.10/node_modules/arepl-backend/python/astunparse/__init__.py", line 3, in <module>
    from six.moves import cStringIO
ModuleNotFoundError: No module named 'six.moves'

and here is the code i was trying to run-
> tpl = 10, 2.2, 'hello', 1+2j, True
a, b, c, d, e = tpl
print('a =', a, ' b =', b, ' c =', c, ' d =', d, ' e =', e)

**Comment by Cresol3127** [comment]
this might help you:
https://github.com/Xirider/LiveCode/pull/22

**Comment by Denny88** [comment]
same issue..

**Comment by ghost** [comment]
Modifying the file in @Cresol3127 #22 PR fixes the issue.

**Comment by lionel-03-zzz** [comment]
I change the code following [https://github.com/Xirider/LiveCode/pull/22](url), but the file goes wrong. Can anyone help me?

![Image](https://github.com/user-attachments/assets/eca25d33-35a5-421b-a3ba-6fe992843819)

**Comment by Cresol3127** [comment]
@lionel-03-zzz I suppose `# type: ignore` in line 3 is causing the issue. That comments actually makes Python ignore the `from six import StringIO` statement. You'll be good to go if you remove that comment from the code.

**Comment by lionel-03-zzz** [comment]
> [@lionel-03-zzz](https://github.com/lionel-03-zzz) I suppose `# type: ignore` in line 3 is causing the issue. That comments actually makes Python ignore the `from six import StringIO` statement. You'll be good to go if you remove that comment from the code.

Thank you. But I face with another problem. It doesn't show the values of x and y unless i print them.

![Image](https://github.com/user-attachments/assets/004d798f-55f2-4477-9872-2d20a1ab3599)

**Comment by Ditokum** [comment]
> > [@lionel-03-zzz](https://github.com/lionel-03-zzz) I suppose `# type: ignore` in line 3 is causing the issue. That comments actually makes Python ignore the `from six import StringIO` statement. You'll be good to go if you remove that comment from the code.
> 
> Thank you. But I face with another problem. It doesn't show the values of x and y unless i print them.
> 
> ![Image](https://github.com/user-attachments/assets/004d798f-55f2-4477-9872-2d20a1ab3599)

so bro did you and how to slove this problem? sorry for 8 months pin

**Comment by lionel-03-zzz** [comment]
> > > [@lionel-03-zzz](https://github.com/lionel-03-zzz) I suppose `# type: ignore` in line 3 is causing the issue. That comments actually makes Python ignore the `from six import StringIO` statement. You'll be good to go if you remove that comment from the code.
> > 
> > 
> > Thank you. But I face with another problem. It doesn't show the values of x and y unless i print them.
> > ![Image](https://github.com/user-attachments/assets/004d798f-55f2-4477-9872-2d20a1ab3599)
> 
> so bro did you and how to slove this problem? sorry for 8 months pin

No.I didn't use LiveCode for long time.

**Comment by Almenon** [comment]
This extension was adapted from my extension, so you can try my extension instead and see if that works better: https://marketplace.visualstudio.com/items?itemName=almenon.arepl
